### ISSUE TITLE
tag at end

### ISSUE THREAD

**Issue by calvinmetcalf** [MattSurabian/aes-gcm-stream#2]
if you put the tag at the end, then you'd only need to buffer the stream on decryption not encryption

**Comment by MattSurabian** [comment]
I went back and forth on this, I'm not opposed to doing the buffering during decryption. I suppose in practice it puts the pain point in a better place.

**Comment by calvinmetcalf** [comment]
It also prevents you from using decrypted but unauthenticated data

**Comment by MattSurabian** [comment]
Ah right! Since we throw the entire buffer into `decipher.update` instead of pushing through chunks one at a time that should prevent the decipher from outputting data until authentication fails as it currently does. I was thinking about how to deal with this over the weekend and actually this handles it perfectly.

Thanks!
